export const SPLASH_SCREEN = 'SPLASH_SCREEN';
export const ONBOARDING_SCREEN = 'ONBOARDING_SCREEN';
export const SIGNIN_SCREEN = 'SIGNIN_SCREEN';
export const TERMSANDCONDITION_SCREEN = 'TERMSANDCONDITION_SCREEN';
export const REVIEW_AGREEMENT_SCREEN = 'REVIEW_AGREEMENT_SCREEN';
export const MANAGE_COACH_SCREEN = 'MANAGE_COACH_SCREEN';
export const HOME_SCREEN = 'HOME_SCREEN';
export const PROFILE_SCREEN = 'PROFILE_SCREEN';
export const COACH_PROFILE_SCREEN = 'COACH_PROFILE_SCREEN';
export const BROWSE_SCREEN = 'BROWSE_SCREEN';
export const CHAT_SCREEN = 'CHAT_SCREEN';
export const CHAT_DETAILS_SCREEN = 'CHAT_DETAILS_SCREEN';
export const COACHES_SCREEN = 'COACHES_SCREEN';
export const MATERIAL_SCREEN = 'MATERIAL_SCREEN';
export const COURSES_SCREEN = 'COURSES_SCREEN';
export const APPOINTMENTS_SCREEN = 'APPOINTMENTS_SCREEN';
export const UPCOMING_APPOINTMENTS_SCREEN = 'UPCOMING_APPOINTMENTS_SCREEN';
export const APPOINTMENT_DETAILS_SCREEN = 'APPOINTMENT_DETAILS_SCREEN';
export const APPOINTMENT_COMPLETION_SCREEN = 'APPOINTMENT_COMPLETION_SCREEN';
export const APPOINTMENT_CONFORMATION_SCREEN =
  'APPOINTMENT_CONFORMATION_SCREEN';
export const COACH_DETAILS_SCREEN = 'COACH_DETAILS_SCREEN';
export const AVAILABILITY_SCREEN = 'AVAILABILITY_SCREEN';
export const VIDEOCALL_SCREEN = 'VIDEOCALL_SCREEN';
export const CREATE_COACH_CHANGE_REQUEST_SCREEN =
  'CREATE_COACH_CHANGE_REQUEST_SCREEN';

export const SLOTS_SCREEN = 'SLOTS_SCREEN';
export const PROGRESS_SCREEN = 'PROGRESS_SCREEN';
export const SLOT_CREATION_SCREEN = 'SLOT_CREATION_SCREEN';
export const SLOT_CREATION_SUCESS_SCREEN = 'SLOT_CREATION_SUCESS_SCREEN';
export const STUDENT_PROGRESS_SCREEN = 'STUDENT_PROGRESS_SCREEN';
export const REPORTS_SCREEN = 'REPORTS_SCREEN';

export const BOTTOM_TAB = 'BOTTOM_TAB';
export const HOME_STACK = 'HOME_STACK';
export const BROWSE_STACK = 'BROWSE_STACK';
export const SESSIONS_STACK = 'SESSIONS_STACK';
export const PROFILE_STACK = 'PROFILE_STACK';
export const COURSES_STACK = 'COURSES_STACK';
export const MATERIAL_STACK = 'MATERIAL_STACK';
export const CHAT_STACK = 'CHAT_STACK';
export const SLOTS_STACK = 'SLOTS_STACK';
export const PROGRESS_STACK = 'PROGRESS_STACK';
export const HOME_DRAWER = 'HOME_DRAWER';
export const COACHE_DRAWER = 'COACHE_DRAWER';

export const STUDENT_GET_STARTED = 'STUDENT_GET_STARTED';
export const COACH_GET_STARTED = 'COACH_GET_STARTED';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
